name = "sk-lean"
version = "0.1.0"
defaultTargets = ["sk-lean"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.19.0-rc2"

[[lean_lib]]
name = "SkLean"
